# Netlify deployment configuration for Angular Portfolio
# This file configures build settings, redirects, and optimizations

[build]
  # Build command to run
  command = "npm run build:deploy"
  
  # Directory to publish (Angular output directory)
  publish = "dist/portfolio/browser"
  
  # Base directory for build (frontend folder)
  base = "frontend"

[build.environment]
  # Node.js version
  NODE_VERSION = "20"
  
  # NPM version
  NPM_VERSION = "10"

# SPA routing - redirect all routes to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    # Content Security Policy
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https:; frame-ancestors 'none';"
    
    # Prevent MIME type sniffing
    X-Content-Type-Options = "nosniff"
    
    # Enable XSS protection
    X-XSS-Protection = "1; mode=block"
    
    # Prevent clickjacking
    X-Frame-Options = "DENY"
    
    # Force HTTPS
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    
    # Referrer policy
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets for 1 year
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache JavaScript and CSS files for 1 year
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Don't cache HTML files
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Enable Brotli compression
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

# Environment variables (set these in Netlify dashboard)
# VITE_API_BASE_URL = "https://your-backend-api.com/api"