"""test migration

Revision ID: 0691df7d5314
Revises: dfc70c57859d
Create Date: 2025-10-24 00:27:33.336399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0691df7d5314'
down_revision: Union[str, None] = 'dfc70c57859d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_meta', sa.Column('avatar_image', sa.String(length=500), nullable=True))
    op.add_column('site_meta', sa.Column('profile_image', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_meta', 'profile_image')
    op.drop_column('site_meta', 'avatar_image')
    # ### end Alembic commands ###
